//
//  JKFoundation.h
//  JKCategories
//
//  Created by Jakey on 16/5/29.
//  Copyright © 2016年 www.skyfox.org. All rights reserved.
//
#if __has_include(<JKCategories/JKFoundation.h>)
#import <JKCategories/NSArray+JKBlock.h>
#import <JKCategories/NSArray+JKSafeAccess.h>
#import <JKCategories/NSBundle+JKAppIcon.h>
#import <JKCategories/NSData+JKAPNSToken.h>
#import <JKCategories/NSData+JKBase64.h>
#import <JKCategories/NSData+JKDataCache.h>
#import <JKCategories/NSData+JKEncrypt.h>
#import <JKCategories/NSData+JKGzip.h>
#import <JKCategories/NSData+JKHash.h>
#import <JKCategories/NSData+JKzlib.h>
#import <JKCategories/NSData+JKPCM.h>
#import <JKCategories/NSDate+JKExtension.h>
#import <JKCategories/NSDate+JKFormatter.h>
#import <JKCategories/NSDate+JKInternetDateTime.h>
#import <JKCategories/NSDate+JKReporting.h>
#import <JKCategories/NSDate+JKUtilities.h>
#import <JKCategories/NSDate+JKZeroDate.h>
#import <JKCategories/NSDate+JKLunarCalendar.h>
#import <JKCategories/NSDateFormatter+JKMake.h>
#import <JKCategories/NSDecimalNumber+JKCalculatingByString.h>
#import <JKCategories/NSDecimalNumber+JKExtensions.h>
#import <JKCategories/NSDictionary+JKBlock.h>
#import <JKCategories/NSDictionary+JKJSONString.h>
#import <JKCategories/NSDictionary+JKMerge.h>
#import <JKCategories/NSDictionary+JKSafeAccess.h>
#import <JKCategories/NSDictionary+JKURL.h>
#import <JKCategories/NSDictionary+JKXML.h>
#import <JKCategories/NSException+JKTrace.h>
#import <JKCategories/NSFileHandle+JKReadLine.h>
#import <JKCategories/NSFileManager+JKPaths.h>
#import <JKCategories/NSHTTPCookieStorage+JKFreezeDry.h>
#import <JKCategories/NSIndexPath+JKOffset.h>
#import <JKCategories/NSInvocation+JKBb.h>
#import <JKCategories/NSInvocation+JKBlock.h>
#import <JKCategories/NSMutableURLRequest+JKUpload.h>
#import <JKCategories/NSNotificationCenter+JKMainThread.h>
#import <JKCategories/NSNumber+JKCGFloat.h>
#import <JKCategories/NSNumber+JKRomanNumerals.h>
#import <JKCategories/NSNumber+JKRound.h>
#import <JKCategories/NSObject+JKAddProperty.h>
#import <JKCategories/NSObject+JKAppInfo.h>
#import <JKCategories/NSObject+JKAssociatedObject.h>
#import <JKCategories/NSObject+JKAutoCoding.h>
#import <JKCategories/NSObject+JKBlocks.h>
#import <JKCategories/NSObject+JKBlockTimer.h>
#import <JKCategories/NSObject+JKEasyCopy.h>
#import <JKCategories/NSObject+JKGCD.h>
#import <JKCategories/NSObject+JKKVOBlocks.h>
#import <JKCategories/NSObject+JKReflection.h>
#import <JKCategories/NSObject+JKRuntime.h>
#import <JKCategories/NSRunLoop+JKPerformBlock.h>
#import <JKCategories/NSSet+JKBlock.h>
#import <JKCategories/NSString+JKBase64.h>
#import <JKCategories/NSString+JKContains.h>
#import <JKCategories/NSString+JKDictionaryValue.h>
#import <JKCategories/NSString+JKEmoji.h>
#import <JKCategories/NSString+JKEncrypt.h>
#import <JKCategories/NSString+JKHash.h>
#import <JKCategories/NSString+JKMatcher.h>
#import <JKCategories/NSString+JKMIME.h>
#import <JKCategories/NSString+JKNormalRegex.h>
#import <JKCategories/NSString+JKPinyin.h>
#import <JKCategories/NSString+JKRemoveEmoji.h>
#import <JKCategories/NSString+JKScore.h>
#import <JKCategories/NSString+JKSize.h>
#import <JKCategories/NSString+JKTrims.h>
#import <JKCategories/NSString+JKURLEncode.h>
#import <JKCategories/NSString+JKUUID.h>
#import <JKCategories/NSString+JKXMLDictionary.h>
#import <JKCategories/NSString+JKStringPages.h>
#import <JKCategories/NSString+JKHTML.h>
#import <JKCategories/NSTimer+JKAddition.h>
#import <JKCategories/NSTimer+JKBlocks.h>
#import <JKCategories/NSURL+JKParam.h>
#import <JKCategories/NSURL+JKQueryDictionary.h>
#import <JKCategories/NSURLConnection+JKSelfSigned.h>
#import <JKCategories/NSURLRequest+JKParamsFromDictionary.h>
#import <JKCategories/NSURLSession+JKSynchronousTask.h>
#import <JKCategories/NSUserDefaults+JKiCloudSync.h>
#import <JKCategories/NSUserDefaults+JKSafeAccess.h>
#else
#import "NSArray+JKBlock.h"
#import "NSArray+JKSafeAccess.h"
#import "NSBundle+JKAppIcon.h"
#import "NSData+JKAPNSToken.h"
#import "NSData+JKBase64.h"
#import "NSData+JKDataCache.h"
#import "NSData+JKEncrypt.h"
#import "NSData+JKGzip.h"
#import "NSData+JKHash.h"
#import "NSData+JKzlib.h"
#import "NSData+JKPCM.h"
#import "NSDate+JKExtension.h"
#import "NSDate+JKFormatter.h"
#import "NSDate+JKInternetDateTime.h"
#import "NSDate+JKReporting.h"
#import "NSDate+JKUtilities.h"
#import "NSDate+JKZeroDate.h"
#import "NSDate+JKLunarCalendar.h"
#import "NSDateFormatter+JKMake.h"
#import "NSDecimalNumber+JKCalculatingByString.h"
#import "NSDecimalNumber+JKExtensions.h"
#import "NSDictionary+JKBlock.h"
#import "NSDictionary+JKJSONString.h"
#import "NSDictionary+JKMerge.h"
#import "NSDictionary+JKSafeAccess.h"
#import "NSDictionary+JKURL.h"
#import "NSDictionary+JKXML.h"
#import "NSException+JKTrace.h"
#import "NSFileHandle+JKReadLine.h"
#import "NSFileManager+JKPaths.h"
#import "NSHTTPCookieStorage+JKFreezeDry.h"
#import "NSIndexPath+JKOffset.h"
#import "NSInvocation+JKBb.h"
#import "NSInvocation+JKBlock.h"
#import "NSMutableURLRequest+JKUpload.h"
#import "NSNotificationCenter+JKMainThread.h"
#import "NSNumber+JKCGFloat.h"
#import "NSNumber+JKRomanNumerals.h"
#import "NSNumber+JKRound.h"
#import "NSObject+JKAddProperty.h"
#import "NSObject+JKAppInfo.h"
#import "NSObject+JKAssociatedObject.h"
#import "NSObject+JKAutoCoding.h"
#import "NSObject+JKBlocks.h"
#import "NSObject+JKBlockTimer.h"
#import "NSObject+JKEasyCopy.h"
#import "NSObject+JKGCD.h"
#import "NSObject+JKKVOBlocks.h"
#import "NSObject+JKReflection.h"
#import "NSObject+JKRuntime.h"
#import "NSRunLoop+JKPerformBlock.h"
#import "NSSet+JKBlock.h"
#import "NSString+JKBase64.h"
#import "NSString+JKContains.h"
#import "NSString+JKDictionaryValue.h"
#import "NSString+JKEmoji.h"
#import "NSString+JKEncrypt.h"
#import "NSString+JKHash.h"
#import "NSString+JKMatcher.h"
#import "NSString+JKMIME.h"
#import "NSString+JKNormalRegex.h"
#import "NSString+JKPinyin.h"
#import "NSString+JKRemoveEmoji.h"
#import "NSString+JKScore.h"
#import "NSString+JKSize.h"
#import "NSString+JKTrims.h"
#import "NSString+JKURLEncode.h"
#import "NSString+JKUUID.h"
#import "NSString+JKXMLDictionary.h"
#import "NSString+JKStringPages.h"
#import "NSString+JKHTML.h"
#import "NSTimer+JKAddition.h"
#import "NSTimer+JKBlocks.h"
#import "NSURL+JKParam.h"
#import "NSURL+JKQueryDictionary.h"
#import "NSURLConnection+JKSelfSigned.h"
#import "NSURLRequest+JKParamsFromDictionary.h"
#import "NSURLSession+JKSynchronousTask.h"
#import "NSUserDefaults+JKiCloudSync.h"
#import "NSUserDefaults+JKSafeAccess.h"
#endif


