//
//  JKFoundation.h
//  JKCategories
//
//  Created by Jakey on 16/5/29.
//  Copyright © 2016年 www.skyfox.org. All rights reserved.
//

#ifndef JKFoundation_h
#define JKFoundation_h

#import "NSArray+JKBlock.h"
#import "NSArray+JKSafeAccess.h"
#import "NSBundle+JKAppIcon.h"
#import "NSData+JKAPNSToken.h"
#import "NSData+JKBase64.h"
#import "NSData+JKDataCache.h"
#import "NSData+JKEncrypt.h"
#import "NSData+JKGzip.h"
#import "NSData+JKHash.h"
#import "NSData+JKzlib.h"
#import "NSData+JKPCM.h"
#import "NSDate+JKCupertinoYankee.h"
#import "NSDate+JKExtension.h"
#import "NSDate+JKFormatter.h"
#import "NSDate+JKInternetDateTime.h"
#import "NSDate+JKReporting.h"
#import "NSDate+JKUtilities.h"
#import "NSDate+JKZeroDate.h"
#import "NSDate+JKLunarCalendar.h"
#import "NSDateFormatter+JKMake.h"
#import "NSDecimalNumber+JKCalculatingByString.h"
#import "NSDecimalNumber+JKExtensions.h"
#import "NSDictionary+JKBlock.h"
#import "NSDictionary+JKJSONString.h"
#import "NSDictionary+JKMerge.h"
#import "NSDictionary+JKSafeAccess.h"
#import "NSDictionary+JKURL.h"
#import "NSDictionary+JKXML.h"
#import "NSException+JKTrace.h"
#import "NSFileHandle+JKReadLine.h"
#import "NSFileManager+JKPaths.h"
#import "NSHTTPCookieStorage+JKFreezeDry.h"
#import "NSIndexPath+JKOffset.h"
#import "NSInvocation+JKBb.h"
#import "NSInvocation+JKBlock.h"
#import "NSMutableURLRequest+JKUpload.h"
#import "NSNotificationCenter+JKMainThread.h"
#import "NSNumber+JKCGFloat.h"
#import "NSNumber+JKRomanNumerals.h"
#import "NSNumber+JKRound.h"
#import "NSObject+JKAddProperty.h"
#import "NSObject+JKAppInfo.h"
#import "NSObject+JKAssociatedObject.h"
#import "NSObject+JKAutoCoding.h"
#import "NSObject+JKBlocks.h"
#import "NSObject+JKBlockTimer.h"
#import "NSObject+JKEasyCopy.h"
#import "NSObject+JKGCD.h"
#import "NSObject+JKKVOBlocks.h"
#import "NSObject+JKReflection.h"
#import "NSObject+JKRuntime.h"
#import "NSRunLoop+JKPerformBlock.h"
#import "NSSet+JKBlock.h"
#import "NSString+JKBase64.h"
#import "NSString+JKContains.h"
#import "NSString+JKDictionaryValue.h"
#import "NSString+JKEmoji.h"
#import "NSString+JKEncrypt.h"
#import "NSString+JKHash.h"
#import "NSString+JKMatcher.h"
#import "NSString+JKMIME.h"
#import "NSString+JKNormalRegex.h"
#import "NSString+JKPinyin.h"
#import "NSString+JKRemoveEmoji.h"
#import "NSString+JKScore.h"
#import "NSString+JKSize.h"
#import "NSString+JKTrims.h"
#import "NSString+JKURLEncode.h"
#import "NSString+JKUUID.h"
#import "NSString+JKXMLDictionary.h"
#import "NSString+JKStringPages.h"
#import "NSString+JKHTML.h"
#import "NSTimer+JKAddition.h"
#import "NSTimer+JKBlocks.h"
#import "NSURL+JKParam.h"
#import "NSURL+JKQueryDictionary.h"
#import "NSURLConnection+JKSelfSigned.h"
#import "NSURLRequest+JKParamsFromDictionary.h"
#import "NSURLSession+JKSynchronousTask.h"
#import "NSUserDefaults+JKiCloudSync.h"
#import "NSUserDefaults+JKSafeAccess.h"

#endif /* JKFoundation_h */
